# Generated by Django 6.0.1 on 2026-01-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='channel',
            field=models.CharField(choices=[('phone', 'phone'), ('email', 'email')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='destination',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='used_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='face_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='verificationselfie',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ot_user_id_5d938f_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['destination', 'created_at'], name='accounts_ot_destina_8cd29e_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['expires_at'], name='accounts_ot_expires_b7415d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname'], name='accounts_us_nicknam_9e69a2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['face_status'], name='accounts_us_face_st_2a683a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationselfie',
            index=models.Index(fields=['uploaded_at'], name='accounts_ve_uploade_54c8c7_idx'),
        ),
    ]
