# Generated by Django 6.0.1 on 2026-01-09 18:36

import accounts.models.photo
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'name'], name='accounts_in_is_acti_b7ab5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'name'], name='accounts_pu_is_acti_702a6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
                'indexes': [models.Index(fields=['name'], name='accounts_re_name_4343f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='accounts.region')),
            ],
            options={
                'ordering': ('region__order', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.photo.user_photo_upload_to)),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_main', 'order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('height_cm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(230)])),
                ('weight_kg', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(250)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('bio', models.TextField(blank=True)),
                ('telegram_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('tiktok_link', models.URLField(blank=True)),
                ('smoking', models.CharField(choices=[('NO', "I don't smoke"), ('YES', 'I smoke'), ('SOMETIMES', 'Sometimes')], default='NO', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='born_profiles', to='accounts.district')),
                ('birth_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='born_profiles', to='accounts.region')),
                ('interests', models.ManyToManyField(related_name='profiles', to='accounts.interest')),
                ('purposes', models.ManyToManyField(related_name='profiles', to='accounts.purpose')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['region', 'name'], name='accounts_di_region__788784_idx'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='uq_district_region_name'),
        ),
        migrations.AddIndex(
            model_name='userphoto',
            index=models.Index(fields=['user', 'is_main'], name='accounts_us_user_id_e5c620_idx'),
        ),
        migrations.AddConstraint(
            model_name='userphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('user',), name='uq_one_main_photo_per_user'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['gender'], name='accounts_us_gender_e8edf5_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['birth_region', 'birth_district'], name='accounts_us_birth_r_844ac3_idx'),
        ),
    ]
