# Generated by Django 6.0.1 on 2026-01-20 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquota',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyquota',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LIKED', 'Liked'), ('SKIPPED', 'Skipped'), ('REJECTED', 'Rejected'), ('MATCHED', 'Matched')], db_index=True, max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('comment_liked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['to_user', 'status', 'updated_at'], name='relationshi_to_user_779b92_idx'), models.Index(fields=['from_user', 'status', 'updated_at'], name='relationshi_from_us_241c9e_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_user', 'to_user'), name='uq_relationship_pair')],
            },
        ),
    ]
