# Generated by Django 6.0.1 on 2026-01-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0002_dailyquota_created_at_dailyquota_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
